# Generated by Django 5.2 on 2025-04-24 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dob', models.DateField(null=True)),
                ('phoneNum', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Provider',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phoneNum', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Law_Firm',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phoneNum', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='accType',
            field=models.CharField(choices=[('CUSTOMER', 'customer'), ('LAW_FIRM', 'law_firm'), ('INSURANCE_PROVIDER', 'insurance_provider'), ('GOVERNMENT', 'government')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='billingAddress',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
