# Generated by Django 5.2 on 2025-04-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0002_customer_government_insurance_provider_law_firm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.CharField(null=True),
        ),
    ]
