# Generated by Django 5.2 on 2025-04-24 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0003_alter_customer_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('coverage', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment.insurance_provider')),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField()),
                ('third_parties', models.CharField()),
                ('details', models.CharField(max_length=512)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment.customer')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment.customer')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assignment.insurance')),
            ],
        ),
    ]
