# Generated by Django 5.2 on 2025-04-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0004_insurance_claims_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='third_parties',
            field=models.CharField(max_length=512),
        ),
    ]
